/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DayScheduleScrollPanel.java
 *
 * Created on May 14, 2009, 3:14:22 PM
 */

package gui;

/**
 *
 * @author kurtisschmidt
 */
public class DayScheduleScrollPanel extends javax.swing.JPanel {

    /** Creates new form DayScheduleScrollPanel */
    public DayScheduleScrollPanel() {
        initComponents();

        for ( int i = 0; i < 24; i++ ) {
            String timePeriod = i + ":00 - " + (i+1) + ":00";

            // Get list of items somehow.
            String thisVariableShouldntExist[] = {"Song1", "Song2", "Song3"};
            scrollPane.add( new HourSchedulePanel( timePeriod, thisVariableShouldntExist ));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

}
